source 'https://rubygems.org'

developer = "alex"
if File.exist? "developer"
  developer = File.read "developer"
end

gem 'rails', '~> 4.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'geocoder'
gem 'linkedin'
gem 'lograge'
gem 'logstash-event'

gem 'fog'

gem 'net-ssh'

gem 'coverband'
gem 'redis'

gem 'dalli'

gem 'application_insights'

# Added for backward compatibility with attr_accessible
gem 'protected_attributes'

gem 'turbolinks'

gem 'cache_digests'

gem 'nio4r'

gem 'unicorn'
gem 'puma'

# Gems used only for assets and not required
# in production environments by default.
gem 'coffee-rails'
gem 'bootstrap-sass'
gem 'jquery-ui-rails'
# gem 'ngmin-rails'
gem 'ngannotate-rails'
gem 'sass-rails'
gem 'compass-rails'
# gem 'turbo-sprockets-rails3'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', :platforms => :ruby
gem 'uglifier'
#  gem 'asset_sync'
gem 'sprockets-derailleur'
gem 'sprockets-image_compressor'
gem 'unf'

group :development, :test do
  gem 'webrick'
  gem 'quiet_assets'
  # Debugging
  gem 'pry'
end

gem "google_visualr"
gem 'balanced'
gem 'stripe'
gem 'paperclip'
# gem 'paperclip-compression'
gem 'aws-sdk'
gem 'data_uri'
gem 'will_paginate'
gem 'pdfkit'
gem 'wicked_pdf'
# gem 'wkhtmltopdf-binary'
gem 'paypal-sdk-rest'

gem 'nokogiri'

gem 'zeroclipboard-rails'

gem 'jquery-rails'

# Authentification

gem 'devise'
gem 'omniauth-facebook'
gem 'omniauth-linkedin'

gem 'flamegraph'
gem 'stackprof'
gem 'twilio-ruby'
gem 'pusher'

# gem 'gibbon', '~> 2.2.0'

gem 'timezone'
gem 'celluloid'
gem 'whenever', :require => false
gem 'httparty'

gem 'useragent'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
#gem 'jbuilder'
gem 'jbuilder'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano

gem 'capistrano'
gem 'capistrano-rails'
gem 'capistrano-rvm'
#gem 'capistrano-rvm'

#gem 'rvm1-capistrano3', require: false

gem 'capistrano-rails-console'

# Deploy with Mina

gem 'mina'
gem 'mina-multistage', require: false
gem 'mina-puma', require: false

#gem "mocha", :group => :test

# Emails

gem 'delayed_job_active_record'
gem 'delayed_job_web'
gem 'daemons'
gem 'postmark-rails'
gem 'postmark-mitt'
gem 'roadie'
gem 'signet'
gem 'listen'
gem 'cancan'

group :production, :staging do
  gem 'newrelic_rpm'
end
gem 'sunspot_rails'
gem 'google-adwords-api'
gem 'google-api-client'
gem 'premailer'
gem 'country_select', github: 'stefanpenner/country_select'
gem "recaptcha", :require => "recaptcha/rails"
gem 'faker'

group :development, :production, :staging, :staging2, :qac do
  #gem 'airbrake'
  gem "bugsnag"
end

gem 'differ'
gem 'awesome_print'
gem 'rack-mini-profiler'
gem 'sanitize'

gem 'open-weather'
gem 'mobile-fu'
gem 'browser'
gem 'ancestry' # use it for tree-based models
gem 'roo'
gem 'roo-xls'
gem 'roo-google'

group :development do
  # To enable livereload download and install the LiveReload for your target browser
  # Run the "guard" command from your console
  # Note: You may get an error that you need to run "zeus start" before livereload will work.
  #       Stop "guard", run "zeus start" and run "guard" again. Don't forget to restart your Rails server
  gem 'guard-livereload', require: false
  gem "bullet"
  gem 'mail_view'
  unless ['dmitry'].include?(developer)
    gem 'sunspot_solr'
    platforms :mri do

    end
  end
end

group :development, :staging, :staging2 do
  # for debugging in RubyMine:
  # if it can't be installed then just comment it out
  # gem 'ruby-debug-ide'
  # gem 'debase'# 0.0.3
  # gem 'ruby-debug-base19x'

  # PROFILING:

  # it's better to build it manually https://github.com/tmm1/perftools.rb
  # gem 'perftools.rb'
  # gem 'rack-perftools_profiler', :require => 'rack/perftools_profiler'
  # sudo apt-get install ruby1.9.1-dev
  # sudo brew    install graphviz ghostscript # osx
  # sudo apt-get install graphviz ps2pdf for ubuntu
end

group :development, :test do
  gem 'launchy'
  gem 'byebug'
end

group :test do
  gem 'delorean'
  gem 'webmock' #, '~> 1.15.1'
  gem 'vcr'
  gem 'rake'
  gem 'rspec' #, '~> 3.0.0.beta2'
  # todo migrate to rspec3 when
  # this pull request is accepted
  # https://github.com/guard/guard-rspec/pull/250
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-zeus'
  gem 'zeus'
  gem 'rspec-rails' #, '~> 3.0.0.beta'
  gem 'factory_girl_rails', require: false
  gem 'shoulda-matchers'
  gem 'capybara'
  #gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
  #gem 'cucumber-rails', :require => false
end

gem 'poltergeist'
gem 'phantomjs' #, :require => 'phantomjs/poltergeist'
gem 'rmagick'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails-dev-tweaks'
  # gem 'passenger'
end

gem 'open_uri_redirections'

group :never_run do
  gem 'sunspot_solr'
  platforms :mri do
    gem 'byebug'
  end
end

gem 'oj'

gem 'posix-spawn'

gem 'transaction_retry'

# sharing button
gem 'social-share-button'
gem 'maxminddb'

# gdrive
gem 'google_drive'

# some nice stuff for params processing
# gem 'strong_parameters'

gem 'lru_redux'

gem 'jwt'

gem 'sucker_punch'
