source 'https://rubygems.org'

developer = "alex"
if File.exist? "developer"
  developer = File.read "developer"
end

gem 'rails', '3.2.17'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'
gem 'geocoder', '~> 1.2.1'
gem 'linkedin'

gem 'fog'

gem 'net-ssh'

gem 'dalli', '~> 2.6.4'

gem 'application_insights'


gem 'cache_digests'

gem 'nio4r', '~> 1.1.1'

gem 'unicorn'
gem 'puma'

# Gems used only for assets and not required
# in production environments by default.
gem 'coffee-rails', '~> 3.2.1'
gem 'bootstrap-sass', '~> 3.0.3.0'
gem 'jquery-ui-rails', '~> 4.1.2'
group :assets do
  gem 'ngmin-rails'
  gem 'sass-rails', '>= 3.2'
  gem 'compass-rails'
  gem 'turbo-sprockets-rails3'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', '>= 0.12.2', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
  #  gem 'asset_sync'
  gem 'sprockets-derailleur'
  gem 'sprockets-image_compressor'
  gem 'unf'
end

group :development, :test do
  gem 'webrick', '~> 1.3.1'
  gem 'quiet_assets'
  # Debugging
  gem 'pry'
end

gem "google_visualr"
gem 'balanced', '~> 1.0'
gem 'stripe'
gem 'paperclip', '~> 4.3'
# gem 'paperclip-compression'
gem 'aws-sdk'
gem 'data_uri'
gem 'will_paginate', '~> 3.0'
gem 'pdfkit'
gem 'wicked_pdf'
# gem 'wkhtmltopdf-binary'
gem 'paypal-sdk-rest'

gem 'nokogiri'

gem 'zeroclipboard-rails'

gem 'jquery-rails'

# Authentification

gem 'devise', '~> 2.2.3'
gem 'omniauth-facebook', '>= 2.0.1'
gem 'omniauth-linkedin'

gem 'flamegraph'
gem 'stackprof', '~> 0.2.7'
gem 'twilio-ruby'
gem 'pusher'

# gem 'gibbon', '~> 2.2.0'

gem 'timezone', '~> 0.3.1'
gem 'celluloid', '~> 0.15.2'
gem 'whenever', :require => false
gem 'httparty'

gem 'paper_trail', '~> 3.0.0'

gem 'useragent'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
#gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano

gem 'capistrano', '~> 3.5.0'
gem 'capistrano-rails', '~> 1.1'
gem 'capistrano-rvm'
#gem 'capistrano-rvm'

#gem 'rvm1-capistrano3', require: false

gem 'capistrano-rails-console'

# Deploy with Mina

gem 'mina'
gem 'mina-multistage', require: false
gem 'mina-puma', require: false

#gem "mocha", :group => :test

# Emails

gem 'delayed_job_active_record'
gem 'delayed_job_web'
gem 'daemons'
gem 'postmark-rails', '~> 0.8.0'
gem 'postmark-mitt'
gem 'roadie', '~> 2.4.3'
gem 'signet', '~> 0.7.1'
gem 'listen', '~> 2.7.0'
gem 'cancan'

gem 'newrelic_rpm'
gem 'sunspot_rails'
gem 'google-adwords-api', '~> 0.19.0'
gem 'google-api-client', '>= 0.7'
gem 'premailer'
gem 'country_select', github: 'stefanpenner/country_select'
gem "recaptcha", :require => "recaptcha/rails"
gem 'faker'

group :development, :production, :staging, :qac do
  #gem 'airbrake'
  gem "bugsnag"
end

gem 'differ'
gem 'awesome_print'
gem 'rack-mini-profiler'
gem 'sanitize'

gem 'open-weather'
gem 'mobile-fu'
gem 'browser', '~> 0.8.0'
gem 'ancestry' # use it for tree-based models
gem 'roo'
gem 'roo-xls'
gem 'roo-google'

group :development do
  gem 'guard-livereload', require: false
  gem "bullet"
  gem 'mail_view', "~> 2.0.4"
  unless ['dmitry'].include?(developer)
    gem 'sunspot_solr'
    platforms :mri do

    end
  end
end

group :development, :staging do
  # for debugging in RubyMine:
  # if it can't be installed then just comment it out
  # gem 'ruby-debug-ide'
  # gem 'debase'# 0.0.3
  # gem 'ruby-debug-base19x'

  # PROFILING:

  # it's better to build it manually https://github.com/tmm1/perftools.rb
  gem 'perftools.rb', '~> 2.0.4'
  gem 'rack-perftools_profiler', '~> 0.6.1', :require => 'rack/perftools_profiler'
  # sudo apt-get install ruby1.9.1-dev
  # sudo brew    install graphviz ghostscript # osx
  # sudo apt-get install graphviz ps2pdf for ubuntu
end

group :development, :test do
  gem 'launchy'
  gem 'byebug'
end

group :test do
  gem 'delorean'
  gem 'webmock' #, '~> 1.15.1'
  gem 'vcr', '~> 3.0.2'
  gem 'rake'
  gem 'rspec', '~> 2.14.1' #, '~> 3.0.0.beta2'
  # todo migrate to rspec3 when
  # this pull request is accepted
  # https://github.com/guard/guard-rspec/pull/250
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-zeus'
  gem 'zeus', '~> 0.15.4'
  gem 'rspec-rails', '~> 2.14.1' #, '~> 3.0.0.beta'
  gem 'factory_girl_rails', '~> 4.5.0', require: false
  gem 'shoulda-matchers'
  gem 'capybara'
  #gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
  #gem 'cucumber-rails', :require => false
end

gem 'poltergeist'
gem 'phantomjs' #, :require => 'phantomjs/poltergeist'
gem 'rmagick'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  # gem 'passenger'
end

gem 'open_uri_redirections', '>= 0.2.1'

group :never_run do
  gem 'sunspot_solr'
  platforms :mri do
    gem 'byebug'
  end
end

gem 'oj'

gem 'posix-spawn'

gem 'transaction_retry'

# sharing button
gem 'social-share-button'
gem 'maxminddb', '0.1.8'

# gdrive
gem 'google_drive'

# some nice stuff for params processing
gem 'strong_parameters'

gem 'lru_redux'
